#!/bin/bash

echo "------ HOOK START - BUILD -------"

COMMIT_DIR="$(cut -d'-' -f3 <<<"$COMMIT_MSG")"
docker build -t $IMAGE_NAME --build-arg COMMIT_DIR=$COMMIT_DIR .

echo "------ HOOK END   - BUILD -------"